---
title: "Hw 3"
author: "Priya Shaji"
date: "9/16/2019"
output:
  html_document: default
  pdf_document:
    extra_dependencies:
      amsmath: null
      inputenc: utf8
subtitle: Chapter LT,Page 444, Question C31
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Question)

For the linear transformation S compute the pre-images.


\[
S: C^3 -> C^3, 
S = \begin{bmatrix}
a\\
b\\
c
\end{bmatrix}
=\begin{bmatrix}
a-2b-c\\
3a-b+2c\\
a+b+2c
\end{bmatrix}
\]


\[
s^-1(\begin{bmatrix}
-2\\
5\\
3
\end{bmatrix})
\]

\[
s^-1(\begin{bmatrix}
-5\\
5\\
7
\end{bmatrix})
\]


Answer 1)

S^-1(A)= preimage of A under S

Since, it's given that S is a linear transformation, let's assume that A is a subset under S,

We have been given the equation where:

\[
Ax=(\begin{bmatrix}
-2\\
5\\
3
\end{bmatrix})
\]

or

\[
Ax=(\begin{bmatrix}
-5\\
5\\
7
\end{bmatrix})
\]


So, let's find the values for x which will satisfy the above two equations

\[
= \begin{bmatrix}
a\\
b\\
c
\end{bmatrix}
\begin{bmatrix}
a-2b-c\\
3a-b+2c\\
a+b+2c
\end{bmatrix}
= \begin{bmatrix}
-2\\
5\\
3
\end{bmatrix}
\]


The values for a,b,c that satisfies is the null space for matrix S.

First, let us create the augmented matrix:



\[
\begin{bmatrix}
a-2b-c\\
3a-b+2c\\
a+b+2c 
\end{bmatrix}
\begin{bmatrix}
-2\\
5\\
3
\end{bmatrix}
\]



\[
\begin{bmatrix}
1 & -2 & -1 & -2\\
3 & -1 & 2 & 5\\
1 & 1 & 2 & 3
\end{bmatrix}
\]

Now, lets reduce the above matrix to reduced row echlon form:

\[
\begin{bmatrix}
1 & -2 & -1 & -2\\
0 & 1 & 1 & 11/5\\
0 & 3 & 3 & 5
\end{bmatrix}
R2^*<- (-3)R1+R2\\
R3^*<- (-1)R1+R3\\
R2^{**}<- {R2^*}*{1/5}
\]


\[
\begin{bmatrix}
1 & 0 & 1 & 0\\
0 & 1 & 1 & 0\\
0 & 0 & 0 & 1
\end{bmatrix},
R3^{**}<-(-3)R2+R3^*
R3^{***}<- R3^{**}*-5/8\\
R3^{****}<- (-1)R1+R3^{***}\\
R2^{***}<-(-11/5)R3^{****}+R2^{**}
R1^*<-2R3^{****}+R1
R1^{**}<-2R2^{***}+R1^*
\]


According to the RCLS theorem, there is a leading one in the last column, therefore, the above system is inconsistent. There are no values for a,b,c which would satisfy the given equation or that will create an element of the pre-image.
`Therefore, the preimage is the empty set.`

Now, let's find the values for x which will satisfy the above two equations

\[
= \begin{bmatrix}
a\\
b\\
c
\end{bmatrix}
\begin{bmatrix}
a-2b-c\\
3a-b+2c\\
a+b+2c
\end{bmatrix}
= \begin{bmatrix}
-5\\
5\\
7
\end{bmatrix}
\]


The values for a,b,c that satisfies is the null space for matrix S.

First, let us create the augmented matrix:



\[
\begin{bmatrix}
1 & -2 & -1 & -5\\
3 & -1 & 2 & 5\\
1 & 1 & 2 & 7
\end{bmatrix}
\]



Now, let's reduced the matrix to reduced row echlon form:



\[
\begin{bmatrix}
1 & -2 & -1 & -5\\
3 & -1 & 2 & 5\\
1 & 1 & 2 & 7
\end{bmatrix},
R2^*<-(-3)R1+R2\\
R3^*<-(-1)R1+R3\\
R2^{**}<-R2^*(1/5)\\
R3^{**}<(-3)R2^{**}+R3^*\\
R1^*<-2R2^{**}+R1
\]


\[
\begin{bmatrix}
1 & 0 & 1 & 3\\
0 & 1 & 1 & 4\\
0 & 0 & 0 & 0
\end{bmatrix}
\]




Therefore for this system , `the solution set is or the required pre image is as follows:`

\[
S^-1
\begin{bmatrix}
-5\\
5\\
7
\end{bmatrix}
=
{\begin{bmatrix}
3\\
4\\
0
\end{bmatrix}
+c
\begin{bmatrix}
-1\\
-1\\
1
\end{bmatrix}
}
=
\begin{bmatrix}
3\\
4\\
0
\end{bmatrix}
+{
\begin{bmatrix}
-1\\
-1\\
1
\end{bmatrix}
}
\]












